moved to approval gate to other workflow

diff --git a/.github/workflows/trigger-other-workflow.yml b/.github/workflows/trigger-other-workflow.yml
--- a/.github/workflows/trigger-other-workflow.yml
+++ b/.github/workflows/trigger-other-workflow.yml
@@ -3,8 +3,24 @@ name: Workflow to trigger another workflow
 on: push
 
 jobs:
+  Approval_Gate:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Recieve Approval
+        shell: bash
+        run: 
+          echo "Approval required to proceed"
+          #approval=$(curl -s -X POST -H "Authorization: token ${{ inputs.token }}" "https://api.github.com/repos/alexanrodrigues/apitriggerworkflow/actions/runs/$GITHUB_RUN_ID/approve")
+
+          #if [ "$approval" = "approved"]; then
+          #  echo "Approved. Workflow will resume."
+          #else
+          #  echo "Denied. Exiting workflow."
+          #  exit 1
+          #fi
   Run_Action:
     runs-on: ubuntu-latest
+    needs: Approval_Gate
     steps:
       - name: Checkout Repository
         uses: actions/checkout@v2
